# All commands below are run from root directory of repository by CodeBuild
version: 0.2

env:
  variables:
    TF_VAR_region: "ap-southeast-2"
    TF_VAR_name: "buildpipeline-prod"
    TF_VAR_kms_key_arns: '["arn:aws:kms:ap-southeast-2:352311918919:key/8d3ffdfd-3292-42d5-a74c-d4ba45921eed"]'
    TF_VAR_ssm_parameter_arns: '["arn:aws:ssm:ap-southeast-2:352311918919:parameter/buildpipeline/*"]'
    TF_VAR_build_docker_image: "352311918919.dkr.ecr.ap-southeast-2.amazonaws.com/dind-terraform-aws"
    TF_VAR_build_docker_tag: "v1.13.1"
    TF_VAR_buildspec: "buildspec-prod.yml"
    TF_VAR_github_repository_owner: "jch254"
    TF_VAR_github_repository_name: "buildpipeline"
    TF_VAR_github_branch_name: "production"
    TF_VAR_dns_name: "buildpipeline-prod.603.nz"
    TF_VAR_acm_arn: "arn:aws:acm:us-east-1:352311918919:certificate/11734027-bace-4fa2-979c-030bef887db6"
    TF_VAR_cache_bucket: "jch254-codebuild-cache/buildpipeline-prod"
    TF_VAR_github_connection_arn: "arn:aws:codeconnections:ap-southeast-2:352311918919:connection/c9e4c26e-c366-4077-82ef-278282f97feb"
    TF_VAR_cloudflare_zone_id: "692b2307a53fc5837e75ee5558cb0ebf"
    REMOTE_STATE_BUCKET: "jch254-terraform-remote-state"
    REMOTE_STATE_REGION: "ap-southeast-4"
    DEPLOY_ENV: "production"
    ARTIFACT_ARCHIVE_BUCKET: "buildpipeline-prod-artifacts"
  parameter-store:
    CLOUDFLARE_API_TOKEN: "/buildpipeline/cloudflare-api-token"
    APP_SECRET: "/buildpipeline/app-secret-prod"

phases:
  install:
    commands:
      # Workaround until CodeBuild/CodePipeline retains file permissions
      - find ./infrastructure -name "*.bash" -exec chmod +x {} \;

  pre_build:
    commands:
      - export APP_VERSION=$CODEBUILD_RESOLVED_SOURCE_VERSION

  build:
    commands:
      - ./infrastructure/deploy-infrastructure.bash
      - ./infrastructure/fetch-artifacts.bash
      - ./infrastructure/upload-artifacts.bash

cache:
   paths:
     - 'infrastructure/.terraform/plugins/**/*'