# All commands below are run from root directory of repository by CodeBuild
version: 0.2

env:
  variables:
    TF_VAR_region: "ap-southeast-2"
    TF_VAR_name: "buildpipeline-test"
    TF_VAR_kms_key_arns: '["arn:aws:kms:ap-southeast-2:982898479788:key/0ec9686b-13a1-40fc-8256-86e8d3503e9c","arn:aws:kms:ap-southeast-2:982898479788:key/f3ccf6b7-dfc4-42d8-82f5-9e2be385f403"]'
    TF_VAR_ssm_parameter_arns: '["arn:aws:ssm:ap-southeast-2:982898479788:parameter/buildpipeline/*","arn:aws:ssm:ap-southeast-2:982898479788:parameter/shared/*"]'
    TF_VAR_build_docker_image: "jch254/docker-node-terraform-aws"
    TF_VAR_build_docker_tag: "latest"
    TF_VAR_buildspec: "buildspec-test.yml"
    TF_VAR_github_repository_owner: "jch254"
    TF_VAR_github_repository_name: "buildpipeline"
    TF_VAR_github_branch_name: "master"
    TF_VAR_dns_name: "buildpipeline-test.603.nz"
    TF_VAR_route53_zone_id: "Z18NTUPI1RKRGC"
    TF_VAR_acm_arn: "arn:aws:acm:us-east-1:982898479788:certificate/65811194-cc89-4926-83c3-199c5c0b6e0c"
    REMOTE_STATE_BUCKET: "603-terraform-remote-state"
    DEPLOY_ENV: "test"
  parameter-store:
    TF_VAR_github_oauth_token: "/shared/github-token"
    APP_SECRET: "/buildpipeline/app-secret"
    GA_ID: "/buildpipeline/ga-id-test"

phases:
  install:
    commands:
      # Workaround until CodeBuild/CodePipeline retains file permissions
      - find ./infrastructure -name "*.bash" -exec chmod +x {} \;
      - ./infrastructure/install.bash

  pre_build:
    commands:
      - export APP_VERSION=$CODEBUILD_RESOLVED_SOURCE_VERSION

  build:
    commands:
      - ./infrastructure/build-artifacts.bash
      - ./infrastructure/run-tests.bash
      - ./infrastructure/deploy-infrastructure.bash
      - ./infrastructure/upload-artifacts.bash
      - ./infrastructure/archive-artifacts.bash
